jonathanjocan/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('portofolio/', views.portofolio, name="portofolio"),
    path('schedule/', include('schedule.urls'), name="schedule"),
]

urlpatterns += staticfiles_urlpatterns()

schedule/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'schedule'

urlpatterns = [
    path('', views.schedule, name="schedule"),
    path('delete/<id>', views.delete_schedule, name="delete"),
]

urlpatterns += staticfiles_urlpatterns()

schedule/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    nama_kegiatan = models.CharField(max_length = 100)
    tempat = models.CharField(max_length = 100)
    kategori = models.CharField(max_length = 100)
    tanggal = models.DateField(auto_now=False, auto_now_add=False)
    jam = models.TimeField(auto_now=False, auto_now_add=False)
    hari = models.CharField(max_length = 10)

    def __str__(self):
        return self.nama_kegiatan
 

schedule/forms.py
from django import forms
from . import models

class DateInput(forms.DateInput):
    input_type = "date"
    # input_formats = ["%d %B %Y"]

class TimeInput(forms.TimeInput):
    input_type = "time"
    # input_formats = ['%H:%M']

class MakeSchedule(forms.ModelForm):
    # tanggal = forms.DateField(widget = forms.DateInput(format = "%d %B %Y"), input_formats = ("%d %B %Y",))
    class Meta:
        model = models.Schedule
        fields = ['nama_kegiatan', 'tempat', 'kategori', 'tanggal', 'jam']

        widgets = {
            'tanggal' : DateInput,
            'jam' : TimeInput
        }

        
   

jonathanjocan/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'jonathanjocan.html')

def portofolio(request):
    return render(request, 'portofolio.html')

schedule/views.py
from django.shortcuts import render, redirect
from . import forms
from django.http import HttpResponse
from .models import Schedule
    
def schedule(request):
    models = Schedule.objects.all()
    if request.method == 'POST':
        form = forms.MakeSchedule(request.POST)
        if form.is_valid():
            object_schedule = form.save()
            object_schedule.hari = object_schedule.tanggal.strftime('%A')
            object_schedule.save()
            return redirect('schedule:schedule')
    else:
        form = forms.MakeSchedule()
    return render(request, 'schedule.html', {'form':form, 'models':models})

def delete_schedule(request, id):
    schedule = Schedule.objects.all().get(id = id)
    schedule.delete()
    return redirect('schedule:schedule')

schedule/templates/schedule.html
{% extends 'base.html'%}
{% load static from staticfiles %}

{% block content%}
    <div id="form_sect">
        <h1><b>Add Schedule</b></h1>
        <div class="form_container d-flex">
            <form class="form_schedule" action="{% url 'schedule:schedule' %}" method="POST">
                {% csrf_token %}
                <table>
                    <tr>
                        {{form}}
                    </tr>
                </table>
                <div class="create_button d-flex">
                    <input type="submit" value="Create Schedule">
                </div>
            </form>
        </div>
    </div>
    <div id="schedule_sect">
        <div class="container-fluid">
            <div class="header">
                <h1><b>My Schedule</b></h1>
            </div>
            <div class="schedule_content d-flex flex-wrap">
                {% for schedule in models %}
                    <div class="schedule_box">
                        <div class=schedule_title>
                            <h1><b>{{schedule.nama_kegiatan}}</b></h1>
                        </div>
                        <p>Place: {{schedule.tempat}}</p>
                        <p>Category: {{schedule.kategori}}</p>
                        <p>Date: {{schedule.tanggal}} </p>
                        <p>Time: {{schedule.jam}}</p>
                        <p>Day: {{schedule.hari}}</p>
                        <div class="d-flex justify-content-center">
                            <a href="{% url 'schedule:delete' id=schedule.id %} #schedule_sect">
                                <div class="button_delete">
                                    <h1><b>Delete</b></h1>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/4b60c8a34d.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,400i,700|Raleway:400,700&display=swap" rel="stylesheet"> 
        <link rel="stylesheet" href="{% static 'jonathanjocan.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Jonathan Chandra</title>
    </head>
    <body>
        <nav id = "navbar" class="navbar navbar-expand-lg navbar-light position-sticky fixed-top">
        <a class="navbar-brand" href="{% url 'home' %}#navbar">
            <div class="d-flex align-items-center">
                <img src="{% static 'logo_jocan.svg' %}">
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'home' %}#navbar"><b>Home</b></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'home' %}#AboutMe_sect"><b>About Me</b></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'home' %}#Education_sect"><b>Education</b></a>    
                </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'home' %}#Experiences_sect"><b>Experiences</b></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'home' %}#Skills_sect"><b>Skills</b></a>    
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'home' %}#Connect_sect"><b>Connect</b></a>    
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'portofolio' %}"><b>Portofolio</b></a>    
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'schedule:schedule' %}"><b>Schedule</b></a>    
            </li>
            </ul>
        </div>
        </nav>
        <a href="#navbar" target="_self">
            <div class="button_up position-fixed">
                <i class="fas fa-angle-double-up"></i>
            </div>
        </a>  
        {% block content%}
        
        {% endblock %}
    </body>
</html>

templates/jonathanjocan.html
{% extends 'base.html'%}
{% load static from staticfiles %}

{% block content%}
  <div id="home_sect">
      <div class="welcome">
          <h2><br>Hi, I'm</h2>
          <h1>Jonathan Chandra</h1>
          <h3><br>Welcome to My Website!<br></h3>
      </div>
        <img src="{% static '\photo\Jocan1.png' %}" class="img-fluid">
  </div>
  <div id="AboutMe_sect">
    <div class="container-fluid d-flex flex-wrap justify-content-between align-items-center">
      <div class="photocard">
        <img src="{% static '\photo\Jocan2.svg' %}" class="img-fluid">
        <h2><b>Jonathan Chandra</b></h2>
        <h4>NPM: 1806204985</h4>
        <h4>University: Universitas Indonesia</h4>
        <h5>E-mail: jonathan.chndr15@gmail.com</h5>
      </div>
      <div class="aboutme">
        <h1><b>About Me</b></h1>
        <p>I'm currently a student majoring in ComputerScience at the Faculty of Computer Science of Universitas Indonesia. Lately, I've been active in several committees and I also currently a staff of the Media Bureau of Student Executive Board at my faculty.
        <br><br>I love to design and sometimes I design or edit some photos just to make people smile. I also love to play badminton since I was in elementary school. Of course, my favorite color is blue as you can see from this website.</p>
        <a href="{% url 'portofolio' %}" target="_self">
          <div class="button_porto">
            <h1><b>View my portofolio</b></h1>
          </div>
        </a>
      </div>
    </div>
  </div>
  <div id="Education_sect">
    <div class="container-fluid">
      <div class="header">
        <h1><b>Education</b></h1>
      </div>
      <div class="education_content">
        <div class="college">
          <h2><b>Universitas Indonesia</b></h2>
          <h3>Majoring Degree of Computer Science (July 2018 - Present)</h3>
          <p>Learned some programming language such as Python and Java.</p>
        </div>
        <div class="high_school">
          <h2><b>Budi Mulia High School Jakarta</b></h2>
          <h3>Majoring in Science (2015 - 2018)</h3>
          <p>Learn about organization by becoming staff of student council (2015 - 2016) and second vice president of student council (2016-2017).</p>
        </div>
      </div>
    </div>
  </div>
  <div id="Experiences_sect">
    <div class="container-fluid">
      <div class="header">
        <h1><b>Experiences</b></h1>
      </div>
      <div class="experiences_content d-flex flex-wrap justify-content-center align-items-center">
        <div class="logo_box d-flex justify-content-center">
          <img src="{% static '\logo\logobem.svg' %}">
        </div>
        <div class="logo_desc">
          <h2><b>BEM Fasilkom UI</b></h2>
          <h3>Staff of Media Bureau (February 2019 - Present)</h3>
          <p>Design posters for social media publication of BEM Fakultas Ilmu Komputer Universitas Indonesia.</p>
        </div>
      </div>
      <div class="experiences_content d-flex flex-wrap justify-content-center align-items-center">
        <div class="logo_box d-flex justify-content-center">
          <img src="{% static '\logo\logocf.svg' %}">
        </div>
        <div class="logo_desc">
          <h2><b>COMPFEST XI</b></h2>
          <h3>Staff of Playground (March 2019 - Present)</h3>
          <p>Search and invite startups to join in Main Event COMPFEST at Playground as an exhibitor.</p>
        </div>
      </div>
    </div>
  </div>
  <div id="Skills_sect">
    <div class="container-fluid">
      <div class="header">
        <h1><b>Skills</b></h1>
      </div>
      <div class="skills_content d-flex flex-wrap justify-content-center">
        <div class="skill_box d-flex flex-column justify-content-between">
          <h1><b>HTML5</b></h1>
          <img src="{% static '\logo\html5.svg' %}">
        </div>
        <div class="skill_box d-flex flex-column justify-content-between">
          <h1><b>CSS3</b></h1>
          <img src="{% static '\logo\css3.svg' %}">
        </div>
        <div class="skill_box d-flex flex-column justify-content-between">
          <h1><b>Java</b></h1>
          <img src="{% static '\logo\java.svg' %}">
        </div>
        <div class="skill_box d-flex flex-column justify-content-between">
          <h1><b>Python</b></h1>
          <img src="{% static '\logo\python.svg' %}">
        </div>
        <div class="skill_box d-flex flex-column justify-content-between">
          <h1><b>Adobe<br>Illustrator</b></h1>
          <img src="{% static '\logo\ai.svg' %}">
        </div>
        <div class="skill_box d-flex flex-column justify-content-between">
          <h1><b>Figma</b></h1>
          <img src="{% static '\logo\figma.svg' %}">
        </div>
      </div>
    </div>
  </div>
  <div id="Connect_sect">
    <div class="connect_content container-fluid d-flex flex-column justify-content-center">
      <h1><b>Connect with Me:</b></h1>
      <div class="icon d-flex justify-content-center">
        <a href="https://www.instagram.com/jonathanchandra15/" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="https://www.linkedin.com/in/jonathan-15/" target="_blank">
          <i class="fab fa-linkedin"></i>
        </a>
      </div>
      <h2>"It's through mistakes that you actually can grow. You have to get bad in order to get good."
        <br>-Paula Scher</h2>
    </div>
  </div>
{% endblock %}

templates/portofolio.html
{% extends 'base.html'%}
{% load static from staticfiles %}

{% block content%}
    <div id="Portofolio_sect">
        <div class="container-fluid">
            <div class="header">
                <h1><b>Portofolio</b></h1>
            </div>
            <div class="portofolio_content d-flex flex-wrap justify-content-center">
                <div class="porto_col d-flex flex-column justify-content-between">
                    <a href="poster1.jpg" target="_blank">
                        <img src="{% static '\poster\poster1.jpg' %}">
                    </a>
                    <a href="poster2.jpg" target="_blank">
                        <img src="{% static '\poster\poster2.jpg' %}">
                    </a>
                </div>
                <div class="porto_col d-flex flex-column justify-content-between">
                    <a href="poster3.jpg" target="_blank">
                        <img src="{% static '\poster\poster3.jpg' %}">
                    </a>
                    <a href="poster4.png" target="_blank">
                        <img src="{% static '\poster\poster4.png' %}">
                    </a>
                </div>
                <div class="porto_col d-flex flex-column justify-content-between">
                    <a href="poster5.jpg" target="_blank">
                        <img src="{% static '\poster\poster5.jpg' %}">
                    </a>
                    <a href="poster6.jpg" target="_blank">
                        <img src="{% static '\poster\poster6.jpg' %}">
                    </a>
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'portofolio' %}#Portofolio_sect" target="_self">
        <div class="button_up position-fixed">
            <i class="fas fa-angle-double-up"></i>
        </div>
    </a>  
{% endblock %}